[package]
default-run = "werewolfd"
name = "werewolfd"
version = "0.1.0"
edition = "2021"

[dependencies]
werewolf-core = { path = "../werewolf-core" }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4", features = ["derive"] }

base64 = "0.22"
blake3 = "1"
x25519-dalek = { version = "2", features = ["static_secrets"] }
chacha20poly1305 = "0.10"
rand_core = { version = "0.6", features = ["getrandom"] }
quinn = "0.11"
rustls = "0.23"
rcgen = "0.13"
ed25519-dalek = { version = "2", features = ["rand_core", "pkcs8"] }
